name: Scan secrets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: trufflehog
        uses: trufflesecurity/trufflehog@v3.88.20
        with:
          extra_args: --debug
